exports.creatures = [
  [
    "ALIENS.png",
    3,
    "bafybeicpmasca5z36vq74dyiavqprkml2i6egvemn5h5agd6kxrbxjnsia",
  ],
  [
    "ARCHERESS.png",
    2,
    "bafybeicqi63kkgyabu4a7gjdqda7cqwh5f7yycwfzoveagxwqcn66dlp5a",
  ],
  [
    "ASIMO.png",
    2,
    "bafybeigt23lgtbiuozy4khsly5fcnjitvcajhzwv6tznqjlgeiqjyjvkoa",
  ],
  [
    "ATHENA.png",
    4,
    "bafybeidsk5qwqoq43x6v34kiw56voa5nfmjtrjbm2ee7esdienfz7bavqq",
  ],
  [
    "BATTLE ORC (1).png",
    3,
    "bafybeiaewcbiikkwcked5frckxfdoeb7q3hm7el2sdzhjnudjnvojzjzxy",
  ],
  [
    "BATTLE ORC (2).png",
    3,
    "bafybeiftwo5nwknnqixvh4o3uzgxz2bclaqmuz6uw3ehqcpkkmiwzwmcsm",
  ],
  [
    "BATTLE ORC.png",
    3,
    "bafybeidlzpmakoreksk7imy3qln74kup36i3dvl3lptvmyqm5limpucaqi",
  ],
  [
    "CERBERUS (1).png",
    2,
    "bafybeietltsoi4p6o362h7bayfd537jbcpcn64dij2xza2vpdkgmp7tx74",
  ],
  [
    "CERBERUS.png",
    2,
    "bafybeihlvivep4yqofvthmzuga76yogmsvbnkfzyg7qishfheyh244deym",
  ],
  [
    "COVEN.png",
    3,
    "bafybeig25vb2mzgrxh2qd3q7g4kaxxllrocp32njojhwdbxmuqwcg7lxki",
  ],
  [
    "DEMOGORGON.png",
    5,
    "bafybeifsdfgnbw4rqqqztcelcjzctpn7hzhfcc7je2dxxxngoutpibcyoq",
  ],
  [
    "DOC CROC.png",
    2,
    "bafybeihhnxr6mllklnqjid3goxlomtp4xws3tlu4miaxrnm6yeesspcecq",
  ],
  [
    "DRAGON.png",
    5,
    "bafybeihghkpkoobsot5pzg6kdqmjtscwqdhfhvmfgnqtvfndi745tbkgdq",
  ],
  [
    "DROIDS.png",
    2,
    "bafybeigvcdxksfw5pnv7fbxdqyfg5gtxzv4mcdcaram2zyv76prtymssdq",
  ],
  [
    "ELVES.png",
    2,
    "bafybeiemwgjyyybdjckcbbzknvcnyhe4guhl37haolpeyeph7pqaigwrbe",
  ],
  [
    "HEIMDALL.png",
    3,
    "bafybeifzur7lqomhlwopewdguubmuwbawumru4zlxmfc4hpuckeefl5mya",
  ],
  [
    "HELLFIRE.png",
    2,
    "bafybeibvmpgi6y2dtcopufalvz73olatdoliy7oqubvigiwn7e5frnocxq",
  ],
  [
    "ICARUS.png",
    2,
    "bafybeigwpvr36ke2po2dx6ap2t74pimpfs4xyllil3umsk7odckxxwa7ie",
  ],
  [
    "KNIGHTED HORSE.png",
    4,
    "bafybeifxonpr5uur5kmwfageqf2m6pnnquz7dfnx64dwcc23vhsugz5jii",
  ],
  [
    "NINJA 2077.png",
    1,
    "bafybeidbafikk7ydns44vqvztpidl2tdnfivhkeakrm7jnmfvm53hwkyjq",
  ],
  [
    "ODYSSEY.png",
    3,
    "bafybeicsuerjofxtctrsuwlzsolxv5rjafani3lawakjrq7oxmecf27poi",
  ],
  [
    "PHANTOMS.png",
    3,
    "bafybeicj4s4obxc5byaehbrcdosmzepjmut46pwcsjy6hzjiyzpbmwjwza",
  ],
  [
    "ROBOREX (1).png",
    4,
    "bafybeid5yg2aji6t2pryt67n2pr4gkrbh5ouo2iweg7mh4nqfwhupxyl44",
  ],
  [
    "ROBOREX.png",
    4,
    "bafybeiavcr67nyp7ybyr3u6pxsygfb6ioxnby7i2ra36sbs7tryiad2yge",
  ],
  [
    "SERPENTINE (1).png",
    3,
    "bafybeidqprkkfqlcpgnc4etqxxl3654v4riika3tbz3vi2ekgifaaowz4y",
  ],
  [
    "SERPENTINE.png",
    3,
    "bafybeiaqdy3a6ypkynenr4prhjjd6egiyytwenrmak24ud22j3rcqlr2gq",
  ],
  [
    "SPACE OCTOPUS.png",
    3,
    "bafybeigovh5mvdjzi3qkfbk54crdsknfzvxedn2kidyzm4bazbz2jl3v6y",
  ],
  [
    "STUART BIG.png",
    2,
    "bafybeidrn4upyc4s5w6tcgnns2ia3c6rzalmc2llm7iqclkxa5xbdjhbia",
  ],
  [
    "TERMINATOR.png",
    3,
    "bafybeicjr7gvfe47agmwvaizjtnwnw7nd32eypifsdhecqwhhhtbna6bii",
  ],
  [
    "UNDEAD ARMY.png",
    4,
    "bafybeiha2bsfhqoxos6c4sspez4l5zjhe5xxufaxamtps6gwlk4roxl3fy",
  ],
  [
    "UNDERWORLD.png",
    2,
    "bafybeigm5d5zhu4rmnd6nbrf3lzzughkh7y53ojxpk5b6wsfwxhpw7dszq",
  ],
  [
    "VECNA (1).png",
    4,
    "bafybeiaqluqww4blxuxsynf6tulnku7fr56raad2ip25teb6d475ywx5ci",
  ],
  [
    "VECNA.png",
    4,
    "bafybeicewk3blp4augssalbtacnbe67qtwfkaupuicgzooospii3cbz4bu",
  ],
  [
    "WITCH.png",
    2,
    "bafybeigj5h3y3bcmzpds4ep55y3olotquaclczcqgovckbysds2pblm46u",
  ],
  [
    "iROBOT.png",
    1,
    "bafybeih5xn2itva3dpggqq4qh7xcojr7rki4vbcb3pgyhmteimt65xp6oa",
  ],
];
